### ISSUE TITLE
Can't find snippet-comment-template... pulling from wrong directory

### ISSUE THREAD

**Issue by codefoster** [mousetraps/vscode-quicksnippet#1]
I see that on extension.js:114 you're trying to do an `fs.readFileSync('snippet-comment-template.txt')` and that is starting in the wrong directory. We need to figure out how to get the context of the file system of the extension.

**Comment by codefoster** [comment]
I'm looking in the node_modules\vscode\vscode.d.ts to figure out where this might be. I'm suspecting it's going to be given to us as part of the extension context.

**Comment by codefoster** [comment]
Aha! ExtensionContext.extensionPath. I'm on the right trail.

**Comment by mousetraps** [comment]
Ahh I don't think I pushed the latest changes to GH. Have you tried the published version?

**Comment by codefoster** [comment]
Aha. Well, push it, push it! :) I was just fixin' to do a PR. I wonder how similar our solutions are. My fork is in codefoster/vscode-quicksnippet

**Comment by codefoster** [comment]
I didn't try the published version. I don't think the version currently in GH has a mechanism for prompting the user for the snippet name, so I'm curious how you did that.

**Comment by mousetraps** [comment]
pushed :smiley:. sorry about that. Right now, the snippet just opens up to the side in a pane so you can edit all the details.
